### ISSUE TITLE
Cordova 5.1.1 - Installation Issue

### ISSUE THREAD

**Issue by sameermaira** [phonegap-build/GAPlugin#90]
I am unable to install the plugin via plugman on cordova 5.1.1. 

Here's my error.

> cordova create hello com.example.hello HelloWorld
> cd hello
> cordova platform add ios
> sudo plugman install --platform ios --project . --plugin https://github.com/phonegap-build/GAPlugin.git

Fetching plugin "https://github.com/phonegap-build/GAPlugin.git" via git clone
Repository "https://github.com/phonegap-build/GAPlugin.git" checked out to git ref "master".
Installing "com.adobe.plugins.GAPlugin" for ios
cordova version not detected (lacks script "/Users/ND_MacAir01/Developer/workspace/smi/hello/cordova/version" ), continuing.
Failed to install 'com.adobe.plugins.GAPlugin':CordovaError: The provided path "/Users/ND_MacAir01/Developer/workspace/smi/hello" is not a Cordova iOS project.
    at new ios_parser (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/cordova/metadata/ios_parser.js:48:15)
    at new PlatformProjectAdapter (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/platforms/platforms.js:61:19)
    at Object.getPlatformProject (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/platforms/platforms.js:97:23)
    at handleInstall (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/install.js:537:36)
    at /usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/install.js:342:28
    at _fulfilled (/usr/local/lib/node_modules/plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/plugman/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/plugman/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/plugman/node_modules/q/q.js:108:17)
The provided path "/Users/ND_MacAir01/Developer/workspace/smi/hello" is not a Cordova iOS project.

**Comment by bheijns** [comment]
Same issue occurs at Phonegap Build service when using CLI 5.1.
